@echo off
title yt-dlp script by retr0gr4d3
echo Step 1: Making venv...
python -m venv venv
echo Step 1: Venv made...
echo[  
echo Step 2: Upgrading pip...
.\venv\Scripts\python.exe -m pip install --upgrade pip
echo Step 2: Pip upgraded...
echo[ 
echo Step 3: Installing dependencies...
.\venv\Scripts\python.exe -m pip install -r requirements.txt
echo Step 3: Requirements installed...
echo[
echo Setup is complete!
cls
run.bat
